### ISSUE TITLE
Bloated npm distribution

### ISSUE THREAD

**Issue by Jameskmonger** [IonicaBizau/clp#14]
Currently, your `test` directory and `.travis.yml` are all being published to npm.

**Comment by IonicaBizau** [comment]
@Jameskmonger I have this on my list: https://github.com/IonicaBizau/dotfiles/issues/25 It will be an automated update in all my repositories. I will have to add the `files` field in my [`packy`](https://github.com/IonicaBizau/packy) configuration. :grin:

**Comment by IonicaBizau** [comment]
@Jameskmonger Adding the `files` array in `package.json`. The update is still in progress, across the repositories. :rocket:

**Comment by IonicaBizau** [comment]
@Jameskmonger In this specific repo, the fix was implemented in #15. :ship: **`4.0.1`** :tada:
